name: Build and Release Android

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  build_apk:
    name: "Build ${{ matrix.arch }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - armeabi-v7a
          - arm64-v8a
          - x86
          - x86_64
      fail-fast: false
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Install dependencies
        run: bun install

      - name: Prebuild
        run: npx expo prebuild --platform android

      - name: Setup Keystore
        run: |
          echo "MYAPP_UPLOAD_STORE_FILE=../../tools/geoshot.keystore" >> android/gradle.properties
          echo "MYAPP_UPLOAD_STORE_PASSWORD=${{ secrets.KEYSTORE }}" >> android/gradle.properties
          echo "MYAPP_UPLOAD_KEY_ALIAS=geoshot" >> android/gradle.properties
          echo "MYAPP_UPLOAD_KEY_PASSWORD=${{ secrets.KEYSTORE }}" >> android/gradle.properties

      - name: Build APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease -PreactNativeArchitectures=${{ matrix.arch }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "app-${{ matrix.arch }}-release"
          path: android/app/build/outputs/apk/release/*.apk

  release:
    name: Create Release
    needs: build_apk
    runs-on: ubuntu-latest
    if: always() && needs.build_apk.result == 'success'
    steps:
      - uses: actions/download-artifact@v4

      - name: Wait for artifacts to sync
        run: |
          for i in {1..15}
          do
            count=$(find . -name "app-release.apk" | wc -l)
            echo "Found $count/4 .apk files"
            if [ "$count" -eq 4 ]; then
              break
            fi
            sleep 4
          done
          echo "Final artifact tree:"
          ls -R .

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            app-armeabi-v7a-release/*.apk
            app-arm64-v8a-release/*.apk
            app-x86-release/*.apk
            app-x86_64-release/*.apk
          generate_release_notes: true
